import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    bn: {
        // Common
        settings: "সেটিংস",
        preferences: "প্রেফারেন্স",
        profile: "প্রোফাইল",
        notifications: "নোটিফিকেশন",
        courses: "কোর্স",
        subscription: "সাবস্ক্রিপশন",
        streak: "দৈনিক স্ট্রিক",
        daily_streak: "দৈনিক গুনগুন স্ট্রিক",
        learn: "শিখুন",
        language: "ভাষা",
        dark_mode: "ডার্ক মুড",
        loading: "লোড হচ্ছে...",
        save: "সংরক্ষণ",
        cancel: "বাতিল",
        confirm: "নিশ্চিত",
        go_back: "ফিরে যান",
        reset: "রিসেট",
        login: "লগইন",
        signup: "সাইন আপ",
        logout: "লগআউট",
        leaderboard: "লিডারবোর্ড",
        shop: "শপ",
        more: "আরও",
        help: "সহায়তা",
        error_fetch_courses: "কোর্স তালিকা লোড করতে সমস্যা হয়েছে",
        reset_course: "কোর্স রিসেট",
        confirm_reset_msg: "আপনি কি নিশ্চিত যে এই কোর্সের সকল প্রগতি মুছে ফেলতে চান?",
        irreversible: "এটি আর ফিরিয়ে আনা সম্ভব নয়।",
        honey_drop: "হানি ড্রপ",
        king_bee_mode: "সুপার কিং বি",
        queen_bee_mode: "সুপার কুইন বি",
        only_for_99: "হন মাত্র 99 টাকায়!",
        hearts_added_msg: "নতুন হানি ড্রপ যোগ করা হয়েছে!",
        heart_refill_5: "5টি হানি ড্রপ রিফিল",
        unlimited_1d: "১ দিনের আনলিমিটেড",
        total_xp: "মোট মধু",
        select_course: "কোর্স নির্বাচন করুন",
        add_course: "কোর্স যোগ করুন",
        your_leaderboard: "লিডারবোর্ড",
        unlock_leaderboard_title: "লিডারবোর্ড আনলক করুন!",
        unlock_leaderboard_desc: "প্রতিযোগিতা শুরু করতে ১০০ টি XP অর্জন করুন",
        connect_now: "কানেক্ট সাজেশন",
        sun: "রবি",
        mon: "সোম",
        tue: "মঙ্গল",
        wed: "বুধ",
        thu: "বৃহ",
        fri: "শুক্র",
        sat: "শনি",
        my_best: "সর্বোচ্চ রেকর্ড",
        consistency_score: "স্ট্রিক স্কোর",
        perfect_progress: "চমৎকার প্রস্তুতি!",
        almost_perfect: "প্রায় কাছাকাছি!",
        good_progress: "ভালো প্রগতি!",
        keep_going: "চালিয়ে যান!",
        getting_started: "শুরু হলো!",
        no_practice_yet: "কোনো রেকর্ড নেই",
        daily: "দৈনিক",
        weekly: "সাপ্তাহিক",
        monthly: "মাসিক",
        yearly: "বার্ষিক",
        week: "সপ্তাহ",

        streak_tagline_0: "শুরু করুন! আজ থেকেই আপনার ধারাবাহিকতা তৈরি করুন।",
        streak_tagline_1_3: "আপনি দারুণ শুরু করেছেন! আপনার ধারাবাহিকতা বজায় রাখুন।",
        streak_tagline_4_10: "অসাধারণ! আপনি ধারাবাহিকভাবে এগিয়ে যাচ্ছেন। থামবেন না।",
        streak_tagline_11_25: "চমৎকার! আপনার ধারাবাহিকতা সত্যিই শক্তিশালী হয়ে উঠছে।",
        streak_tagline_legend: "অবিশ্বাস্য! আপনি একজন স্ট্রিক লেজেন্ড। এভাবেই চালিয়ে যান।",

        // Settings
        pref_settings: "ব্যক্তিগত অভিজ্ঞতা",
        pref_desc: "আপনার ব্যক্তিগত ব্যবহারের অভিজ্ঞতা কাস্টমাইজ করুন",
        dark_mode_desc: "চোখের আরামের জন্য কালো থিম ব্যবহার করুন",
        study_anim: "স্টাডি পেজ অ্যানিমেশন",
        study_anim_desc: "আপনার পছন্দের মৌমাছি অ্যানিমেশন নির্বাচন করুন",
        lang_desc: "আপনার পছন্দের ভাষা নির্বাচন করুন",
        sound_effects: "সাউন্ড ইফেক্ট",
        sound_effects_desc: "শেখার সময় শব্দ সংকেত চালু বা বন্ধ রাখুন",
        sparkle_effects: "স্পার্কল ইফেক্টস",
        sparkle_desc: "সঠিক উত্তরের সময় ঝলমলে আবহ তৈরি করুন",

        profile_settings: "প্রোফাইল সেটিংস",
        profile_desc: "আপনার ব্যক্তিগত তথ্য এবং প্রোফাইল দৃশ্যমানতা পরিচালনা করুন",
        public_profile: "পাবলিক প্রোফাইল",
        public_profile_desc: "অন্যান্য ব্যবহারকারীরা আপনার শেখার অগ্রগতি দেখতে পারবে",
        private_profile_msg: "এই প্রোফাইলটি বর্তমানে প্রাইভেট করা আছে",
        change_pic: "পরিবর্তন করুন",
        profile_picture: "প্রোফাইল ছবি",
        upload_new_pic: "একটি নতুন প্রোফাইল ছবি আপলোড করুন",
        bouncing_bee: "বাউন্সিং বী 🐝",
        lounging_bee: "লাউঞ্জিং বী 🐝💤",
        looking_bee: "লুকিং বী 🐝👀",
        flying_bee: "ফ্লাইং বী 🐝✈️",
        happy_bee: "হ্যাপি বী 🐝😊",
        random_animation: "বি অ্যানিমেশন",
        no_animation: "কোনো অ্যানিমেশন নয়",
        under_development: "এই সেকশনটি বর্তমানে ডেভেলপমেন্টাধীন আছে",
        section_settings: "সেটিংস",
        reset_success: "কোর্স প্রগতি রিসেট করা হয়েছে",
        reset_error: "রিসেট করতে সমস্যা হয়েছে",
        sound_on: "সাউন্ড ইফেক্ট চালু করা হয়েছে",
        sound_off: "সাউন্ড ইফেক্ট বন্ধ করা হয়েছে",
        upload_error: "ছবি আপলোড করতে সমস্যা হয়েছে",
        profile_updated: "প্রোফাইল আপডেট করা হয়েছে",
        on: "চালু",
        off: "বন্ধ",
        // Profile
        change_cover: "কভার পরিবর্তন করুন",
        current_streak: "বর্তমান স্ট্রিক",
        buzz_streak: "দৈনিক গুনগুন স্ট্রিক",
        days: "দিন",
        learner: "শিক্ষার্থী",
        welcome_tagline: "শেখার যাত্রায় আপনাকে স্বাগতম",
        joined: "যোগদান",
        earned_shield: "অর্জিত শিল্ড",
        level: "লেভেল",
        efficiency: "নির্ভুলতা",
        my_courses: "আমার কোর্সসমূহ",
        see_all: "সবগুলো দেখুন",
        progress: "অগ্রগতি",
        chapters: "অধ্যায়",
        start_course: "কোর্স শুরু করুন",
        recent_activity: "সাম্প্রতিক কার্যকলাপ",
        practice_xp: "অনুশীলন সম্পন্ন করে XP পেয়েছেন",
        reward_gems: "পুরস্কারস্বরূপ মধুরেণু পেয়েছেন",
        lost_hearts: "ভুল উত্তরের জন্য হানি ড্রপ হারিয়েছেন",
        refilled_hearts: "হানি ড্রপ রিফিল হয়েছে",
        no_activity: "কোনো কার্যকলাপের রেকর্ড পাওয়া যায়নি।",
        edit_profile: "প্রোফাইল সম্পাদন করুন",
        full_name: "পুরো নাম",
        email: "ইমেইল",
        designation: "পদবী",
        dept: "বিভাগ/দপ্তর",
        bio: "আপনার সম্পর্কে",
        about_me: "নিজের সম্পর্কে লিখুন",
        location: "অবস্থান",
        phone_number: "ফোন নম্বর",
        gender: "লিঙ্গ",
        male: "পুরুষ",
        female: "নারী",
        other: "অন্যান্য",
        age: "জন্ম সাল",
        i_am: "আমি একজন",
        student: "শিক্ষার্থী",
        job_seeker: "চাকরিপ্রার্থী",
        job_holder: "চাকরিজীবী",
        education: "শিক্ষাগত যোগ্যতা",
        below_class_5: "৫ম শ্রেণীর নিচে",
        class_6_10: "৬ষ্ঠ-১০ম শ্রেণী",
        intermediate: "এইচএসসি/ডিপ্লোমা",
        graduate: "স্নাতক",
        post_graduate: "স্নাতকোত্তর",
        update_error: "প্রোফাইল আপডেট করতে সমস্যা হয়েছে।",
        confirm_logout_msg: "আপনি কি নিশ্চিত যে লগআউট করতে চান?",
        logout_success: "সাফল্যের সাথে লগআউট করা হয়েছে",
        logout_error: "লগআউট করতে সমস্যা হয়েছে",

        tab_general: "সাধারণ",
        tab_analyze: "এনালিটিক্স",
        tab_activity: "নটিফিকেশন",
        tab_certificates: "সার্টিফিকেট",
        tab_connection: "সংযোগ",
        subtab_my: "কানেকশন",
        subtab_suggest: "শিক্ষার্থী খুঁজুন",
        subtab_inbox: "ইনবক্স",
        subtab_battle: "ব্যাটল ওয়ার",
        filter_all: "কানেকশন",
        filter_received: "প্রাপ্ত",
        filter_sent: "পাঠানো",
        filter_blocked: "ব্লক লিস্ট",

        certification: "সার্টিফিকেশন",
        earned_certificates: "সার্টিফিকেট",
        invite_learner: "বন্ধুদের আমন্ত্রণ করুন",
        invite_success: "কপি হয়েছে!",
        invite_message: "এখনই বন্ধুদের আমন্ত্রণ জানান, আর বোনাস হিসেবে পান ৫টি হানি ড্রপ!",
        invite_share_cta: "শেয়ার করুন",
        invite_share_text: "হ্যালো! আমি BeeLesson-এর সাথে শেখা শুরু করেছি। এটি বাংলাদেশের প্রথম গেমিফাইড লার্নিং প্ল্যাটফর্ম, যা আপনাকে দেবে এক নতুন শেখার অভিজ্ঞতা। তাই আর দেরি না করে আজই যোগ দিন BeeLesson কমিউনিটিতে এবং উপভোগ করুন শেখার এক নতুন যাত্রা!",
        no_certificates: "আপনি এখনও কোনো সার্টিফিকেট অর্জন করেননি।",
        save_percentage_yearly: "১৬% সাশ্রয়",
        super_bee_title: "সুপার বি প্রিমিয়াম",
        order_details: "অর্ডারের বিবরণ",
        payment_method: "পেমেন্ট পদ্ধতি",
        tax: "ট্যাক্স",
        total_due_today: "মোট পরিমাণ",
        discount_label: "ডিসকাউন্ট",
        promo_success_msg: "সফল",
        enter_promo_code: "কুপন কোড",
        apply: "প্রয়োগ",
        remove: "মুছে ফেলুন",




        analysis_ov: "অ্যাক্টিভিটি অ্যানালাইসিস",
        total_time: "মোট সময়",
        right_answers: "সঠিক উত্তর",
        wrong_answers: "ভুল উত্তর",
        daily_xp: "অর্জিত মধু",
        accuracy: "নির্ভুলতা",
        last_7_days: "গত ৭ দিন",
        last_15_days: "গত ১৫ দিন",
        last_30_days: "গত ৩০ দিন",
        all_time: "সকল",
        minutes: "মিনিট",
        tab_connection: "কানেকশন",
        search_learner: "শিক্ষার্থী খুঁজুন...",
        send_request: "অনুরোধ পাঠান",
        pending_requests: "পেন্ডিং রিকোয়েস্ট",
        my_connections: "আমার শুভাকাঙ্ক্ষী",
        accept: "গ্রহণ করুন",
        decline: "বাতিল",
        no_connections: "এখনো কোনো কানেকশন নেই",
        learner_profile: "শিক্ষার্থীর প্রোফাইল",
        rank: "র‍্যাঙ্ক",
        location: "অবস্থান",
        bio: "পরিচয়",
        close: "বন্ধ করুন",
        search_chat: "সার্চ করুন",
        suggest_connection: "কারা হতে পারে বন্ধু?",
        sent_connection: "পাঠানো অনুরোধ",
        suggestions_for_you: "আপনার জন্য কিছু সাজেশন",
        no_suggestions: "এখনো কোনো সাজেশন নেই",
        view_all_suggestions: "সব সাজেশন দেখুন",
        no_sent_requests: "কোনো পেন্ডিং অনুরোধ নেই",
        analysis_locked_title: "অ্যানালিটিক্স লক করা আছে",
        analysis_locked_desc: "ধারাবাহিক ভাবে ৩ দিন অনুশীলন করলে আপনার পারফরমেন্স চার্টগুলো আনলক হবে।",
        days_earned: "{count} দিন পূর্ণ হয়েছে",
        daily_honey: "দৈনিক সংগৃহীত মধু",
        earned: "অর্জিত",
        learning_pattern: "পড়াশোনার ধরণ",
        coming_soon: "শীঘ্রই আসছে...",
        lessons_completed: "সম্পন্ন লেসন",
        activity_log: "অ্যাক্টিভিটি লগ",
        notifications: "নোটিফিকেশন",
        empty_activity: "কোনো কার্যক্রম পাওয়া যায়নি",
        empty_notif: "নতুন কোনো নোটিফিকেশন নেই",
        notif_unread: "টি আনরিড",
        notif_all_read: "সব পড়া হয়েছে",
        notif_mark_all: "সব পড়া হল",
        filter_all_notif: "সব",
        filter_achievements: "অ্যাচিভমেন্ট",
        filter_social: "সোশ্যাল",
        filter_system: "সিস্টেম",
        no_notifications: "কোনো নটিফিকেশন নেই",
        earlier: "আগে",

        notif_settings: "নোটিফিকেশন সেটিংস",
        notif_desc: "আপনি কিভাবে আপডেট এবং স্মরণিকা পাবেন তা নিয়ন্ত্রণ করুন",
        push_notif: "পুশ নোটিফিকেশন",
        push_notif_desc: "আপনার মোবাইল বা ব্রাউজারে সরাসরি আপডেট পান",
        email_notif: "ইমেল নোটিফিকেশন",
        email_notif_desc: "সাপ্তাহিক প্রগতি রিপোর্ট এবং গুরুত্বপূর্ণ আপডেট পান",
        daily_reminder: "ডেইলি রিমাইন্ডার",
        daily_reminder_desc: "প্রতিদিন শিখতে থাকার জন্য একটি স্মারক পান",
        active_membership: "সক্রিয় মেম্বারশিপ",
        no_active_membership: "কোনো সক্রিয় মেম্বারশিপ নেই",
        expires_on: "মেয়াদ শেষ হবে",
        unlock_premium_visit_shop: "প্রিমিয়াম ফিচার আনলক করতে শপে যান",
        cancelled_not_renew: "⚠ বাতিল করা হয়েছে (রিনিউ হবে না)",
        cancel_membership: "মেম্বারশিপ বাতিল করুন",
        cancel_membership_msg: "আপনি কি নিশ্চিত যে আপনি মেম্বারশিপ বাতিল করতে চান? আপনার বর্তমান মেয়াদ শেষ না হওয়া পর্যন্ত সুবিধাগুলো সচল থাকবে এবং এরপর আর রিনিউ হবে না।",
        yes_cancel: "হ্যাঁ, বাতিল করুন",
        successfully_cancelled: "পদক্ষেপ সফল হয়েছে",
        error_cancelling: "বাতিল করতে সমস্যা হয়েছে",

        course_settings: "কোর্স সেটিংস",
        course_settings_desc: "আপনার এনরোল করা কোর্সসমূহ পরিচালনা করুন",
        completed: "সম্পন্ন",
        no_courses: "কোনো কোর্স পাওয়া যায়নি",
        no_courses_desc: "আপনি এখনও কোনো কোর্সে এনরোল করেননি।",
        warning_reset: "সতর্কতা: প্রগতি রিসেট বা কোর্স ডিলিট করলে তা আর পুনরুদ্ধার করা সম্ভব নয়।",

        // Shop
        shop_title: "বি লেসন শপ",
        shop_subtitle: "আপনার শেখার অভিজ্ঞতাকে আরও সমৃদ্ধ করুন",
        super_membership: "সুপার মেম্বারশিপ",
        super_desc: "আপনি এখন আনলিমিটেড হানি ড্রপ এবং অ্যাড-ফ্রি অভিজ্ঞতা উপভোগ করছেন।",
        active_super: "সুপার সদস্যপদ সক্রিয়",
        unlimited_hearts: "আনলিমিটেড হানি ড্রপ",
        ad_free: "অ্যাড-ফ্রি লার্নিং",
        quick_progress: "দ্রুত প্রগ্রেস",
        special_badge: "স্পেশাল ব্যাজ",
        monthly: "মাসিক",
        yearly: "বার্ষিক",
        discount: "-20%",
        gem_exchange: "মধুরেণু এক্সচেঞ্জ",
        exchange: "এক্সচেঞ্জ",
        gem_packs: "মধুরেণু প্যাক",
        popular: "জনপ্রিয়",
        best_value: "সেরা মূল্য",
        confirm_payment: "পেমেন্ট নিশ্চিত করুন",
        payment_desc: "আপনার অর্ডারটি সম্পন্ন করতে পেমেন্ট মেথড নির্বাচন করুন",
        order_summary: "অর্ডার সামারি",
        item: "আইটেম",
        total_price: "মোট মূল্য",
        pay_now: "পেমেন্ট সম্পন্ন করুন",
        insufficient_gems: "আপনার কাছে যথেষ্ট মধুরেণু নেই।",
        hearts_added: "টি নতুন হানি ড্রপ যোগ করা হয়েছে!",
        hearts_added_msg: "হানি ড্রপ যোগ করা হয়েছে",
        gems_added: "টি মধুরেণু যোগ করা হয়েছে!",
        congrats_premium: "অভিনন্দন! আপনি এখন সুপার সাবস্ক্রাইবার।",
        payment_failed: "পেমেন্ট সফল হয়নি। পুনরায় চেষ্টা করুন।",
        loading_shop: "লোড হচ্ছে...",
        active: "সক্রিয়",
        activate: "সক্রিয় করুন",
        bkash: "বিকাশ",
        nagad: "নগদ",
        quick_honey_drop: "কুইক হানি ড্রপ",
        enjoy_1day_unlimited: "পুরো 1 দিন আনলিমিটেড হানি ড্রপ উপভোগ করুন!",
        recharge_1day: "রিচার্জ 1 দিন",
        exchange_success_title: "সফল হয়েছে!",
        exchange_success_desc: "আপনার মধুরেণু সফলভাবে হানি ড্রপে রূপান্তরিত হয়েছে।",
        insufficient_pollen_title: "পর্যাপ্ত মধুরেণু নেই",
        insufficient_pollen_desc: "হানি ড্রপ এক্সচেঞ্জ করতে কমপক্ষে {amount}টি মধুরেণু প্রয়োজন।",
        start_learning_earn_pollen: "পড়া শুরু করুন",
        view_mode: "মোড দেখুন",
        not_now: "এখন নয়",
        confirm_exchange_title: "এক্সচেঞ্জ কনফার্ম করুন",
        confirm_exchange_desc: "মধুরেণু দিয়ে হানি ড্রপ পাওয়ার জন্য কনফার্ম করুন",
        yes_confirm: "হ্যাঁ, কনফার্ম",
        no: "না",
        unlocked_all_features: "সব ফিচার আনলক করা আছে",
        unlimited_hearts_msg: "শিখতে থাকুন আনলিমিটেড হানি ড্রপ নিয়ে",
        unlimited_hearts_active_msg: "আপনার আনলিমিটেড হানি ড্রপ সক্রিয় আছে। 👑",
        male_bee_title: "কিং বি",
        female_bee_title: "কুইন বি",
        queen_bee_feature_1: "ভুল করলেও শেখা থামবে না। আনলিমিটেড হানি ড্রপ।",
        please_login: "অনুগ্রহ করে লগইন করুন।",
        unlimited_active_already: "আপনার আনলিমিটেড হানি ড্রপ আগে থেকেই সক্রিয় আছে।",
        already_in_mode: "আপনি বর্তমানে {mode} মুড-এ আছেন! 👑",
        conversion_error: "কনভার্ট করতে সমস্যা হয়েছে।",
        data_not_found: "তথ্য পাওয়া যায়নি।",
        something_went_wrong: "দুঃখিত, সমস্যা হয়েছে।",
        session_not_found: "সেশন পাওয়া যায়নি। আবার লগইন করুন।",
        payment_processing: "পেমেন্ট প্রসেসিং হচ্ছে...",
        subscription_success: "সাবস্ক্রিপশন সফল! আপনি এখন মেম্বার! 👑",
        oneday_recharge_success: "১ দিনের রিচার্জ সফল! আনলিমিটেড হানি ড্রপ উপভোগ করুন 🍯",
        payment_process_failed: "পেমেন্ট প্রসেস করা সম্ভব হয়নি।",
        write_msg: "বার্তা লিখুন...",
        today: "আজ",
        yesterday: "গতকাল",
        delete_msg: "ডিলিট করুন",
        survey_continue: "চালিয়ে যান",
        survey_complete: "সম্পূর্ণ করুন",
        step: "ধাপ",

        // Gem Pack Labels
        gem_pocket: "মধুরেণু পকেট",
        gem_chest: "মধুরেণু চেস্ট",
        gem_cart: "মধুরেণু কার্ট",
        gem_vault: "মধুরেণু ভল্ট",
        pollen: "মধুরেণু",

        // Leaderboard Page
        unlock_leaderboard: "লিডারবোর্ড আনলক করুন",
        reach_xp_to_unlock: "প্রতিযোগিতায় অংশ নিতে আরও {xp} মধু অর্জন করুন।",
        xp_earned_so_far: "{xp} মধু অর্জিত",
        target_xp: "{xp} মধু",
        how_to_earn_xp: "মধু কীভাবে অর্জন করবেন?",
        earn_xp_desc: "প্রতিটি অধ্যায় বা কুইজ সম্পন্ন করলে মধু পাবেন। নির্ভুল উত্তর দিলে বেশি মধু।",
        bee_ranks: "বি-র র‍্যাঙ্ক",
        bee_ranks_desc: "Bee Kid → Warrior → Master → Legendary। প্রতি সপ্তাহে শীর্ষরা পরবর্তী লিগে ওঠে।",
        start_competition: "প্রতিযোগিতা শুরু করুন",
        start_competition_desc: "বন্ধুদের সাথে প্রতিযোগিতা করুন এবং দেশের সেরা শিক্ষার্থীদের তালিকায় নাম তুলুন।",
        start_learning_btn: "শেখা শুরু করুন",
        reached_legendary: "আপনি Bee Legendary-তে পৌঁছে গেছেন! 🎉",
        complete_xp_to_join: "{tier} লিগে যোগ দিতে আরও +{xp} মধু",
        leaderboard_table_rank: "#",
        leaderboard_table_learner: "শিক্ষার্থী",
        leaderboard_table_progress: "অগ্রগতি",
        leaderboard_table_pollen: "মোট মধু",
        empty_tier: "এই লিগে এখনো কোনো শিক্ষার্থী নেই। পড়াশোনা শুরু করুন এবং জায়গা করে নিন!",
        leaderboard_share_msg: "আমি BeeLesson-এর {tier} লিগে #{rank} র‍্যাঙ্কে আছি! তুমি কি আমার {xp} মধু টপকাতে পারবে?",
        share_rank_tooltip: "আপনার র‍্যাঙ্ক শেয়ার করুন",

        // Navbar
        learn: "শিখুন",
        shop: "শপ",
        leaderboard: "লিডারবোর্ড",
        login_btn: "লগইন করুন",

        // Courses
        courses_title: "আপনার পছন্দের",
        courses_highlight: "কোর্সসমূহ",
        courses_suffix: "যুক্ত করুন",
        all_courses: "সব কোর্স",
        no_courses_cat: "এই ক্যাটাগরিতে কোনো কোর্স পাওয়া যায়নি।",
        course_rating: "কোর্স রেটিং",
        students_count: "শিক্ষার্থী সংখ্যা",
        search_courses: "কোর্স খুঁজুন...",
        try_different_filter: "আলাদা ক্যাটাগরি বা কীওয়ার্ড চেষ্টা করুন",
        reset_filters: "রিসেট করুন",
        no_courses_found: "কোনো কোর্স পাওয়া যায়নি",
        grid_view: "গ্রিড ভিউ",
        list_view: "লিস্ট ভিউ",
        sort_by: "সাজান:",
        sort_popularity: "জনপ্রিয়তা",
        sort_rating: "রেটিং",
        sort_newest: "নতুন কোর্স",

        // Categories
        cat_digital_security_literacy: "ডিজিটাল লিটারেসি ও নিরাপত্তা",
        cat_legal_rights: "আইনি সচেতনতা ও নাগরিক অধিকার",
        cat_finance_banking: "আর্থিক সচেতনতা ও স্মার্ট ব্যাংকিং",
        cat_career_skills: "ক্যারিয়ার ও দক্ষতা",
        cat_mental_health: "মানসিক স্বাস্থ্য ও আত্মউন্নয়ন",

        // Landing Page Generic
        proven_title: "বৈজ্ঞানিকভাবে প্রমাণিত",
        proven_desc: "আমাদের পাঠদান পদ্ধতি গবেষণালব্ধ এবং কার্যকর। প্রতিটি পাঠ ডিজাইন করা হয়েছে যাতে আপনি দ্রুত এবং আনন্দদায়ক উপায়ে শিখতে পারেন।",
        footer_copy: "2024 বি লেসন. সকল স্বত্ব সংরক্ষিত।",

        reset_filters: "সব রিসেট করুন",

        // Help Center
        help_center: "হেল্প সেন্টার",
        how_can_we_help: "কিভাবে আমরা আপনাকে সাহায্য করতে পারি?",
        search_placeholder: "আপনার প্রশ্নটি লিখুন (যেমন: সার্টিফিকেট, পেমেন্ট...)",
        faq_title: "সচরাচর জিজ্ঞাসিত প্রশ্ন",
        faq_subtitle: "আপনার প্রয়োজনীয় তথ্যটি নিচে খুঁজে দেখুন",
        need_direct_help: "সরাসরি সহায়তা প্রয়োজন?",
        mail_support_desc: "আপনার কোনো বিশেষ প্রশ্ন থাকলে আমাদের সাপোর্ট টিমকে মেইল করতে পারেন।",
        no_results_found: "এর সাথে সম্পর্কিত কিছু খুঁজে পাওয়া যায়নি",
        help_footer: "© ২০২৪ বি লেসন (BeeLesson) হেল্প সেন্টার",
        clear_search: "সার্চ মুছুন",

        // Privacy Page
        privacy_policy: "প্রাইভেসি পলিসি",
        privacy_desc: "আপনার তথ্যের সুরক্ষা আমাদের প্রধান অগ্রাধিকার। বি লেসন (BeeLesson)-এ আমরা কীভাবে আপনার তথ্য সংগ্রহ এবং ব্যবহার করি তা নিচে দেওয়া হলো:",
        p_section_1_title: "১. তথ্য সংগ্রহ",
        p_section_1_desc: "আমরা আপনার নাম, ইমেইল, প্রোফাইল ছবি, জন্ম সাল এবং পেশাগত তথ্য সংগ্রহ করি। এছাড়াও আপনার শেখার অগ্রগতি, স্ট্রিক এবং হানি ড্রপের তথ্য সংরক্ষিত হয়।",
        p_section_2_title: "২. তথ্যের ব্যবহার",
        p_section_2_desc: "আপনার শেখার অভিজ্ঞতা উন্নত করতে, লিডারবোর্ড র‍্যাঙ্কিং নির্ধারণ করতে এবং প্ল্যাটফর্মের নিরাপত্তা নিশ্চিত করতে আমরা এই তথ্যগুলো ব্যবহার করি।",
        p_section_3_title: "৩. ডাটা শেয়ারিং",
        p_section_3_desc: "আমরা আপনার ডাটা বিক্রি করি না। শুধুমাত্র আপনার পাবলিক প্রোফাইলের অংশ হিসেবে আপনার নাম ও অগ্রগতি অন্য শিক্ষার্থীরা দেখতে পাবে।",
        p_section_4_title: "৪. ডাটা সিকিউরিটি",
        p_section_4_desc: "আমরা আধুনিক সার্ভিস (যেমন: Supabase) ব্যবহার করে আপনার তথ্য সুরক্ষিত রাখি। আপনার গোপনীয়তা আমাদের কাছে পবিত্র।",
        p_section_5_title: "৫. আপনার নিয়ন্ত্রণ",
        p_section_5_desc: "যেকোনো সময় আপনি প্রোফাইল আপডেট বা ডিলিট করতে পারেন। কারো সাথে তথ্য শেয়ার করতে না চাইলে প্রোফাইল 'প্রাইভেট' করে রাখতে পারেন।",
        p_contact_us: "যোগাযোগ: support@beelesson.com",

        // Terms Page
        terms_title: "টার্মস এবং কন্ডিশনস",
        terms_desc: "বি লেসন (BeeLesson)-এ আপনাকে স্বাগতম। আমাদের সার্ভিস ব্যবহারের মাধ্যমে আপনি নিম্নলিখিত শর্তাবলীতে সম্মত হচ্ছেন।",
        t_section_1_title: "১. অ্যাকাউন্ট এবং নিবন্ধন",
        t_section_1_desc: "সার্ভিস ব্যবহারের জন্য আপনাকে একটি নির্ভুল অ্যাকাউন্ট তৈরি করতে হবে। আপনার অ্যাকাউন্টের তথ্যের গোপনীয়তা রক্ষার দায়িত্ব আপনার।",
        t_section_2_title: "২. সেবার ব্যবহার",
        t_section_2_desc: "প্ল্যাটফর্মের কোনো কন্টেন্ট জালিয়াতি, কপি বা অনুমতি ছাড়া অন্য কোথাও শেয়ার করা কঠোরভাবে নিষিদ্ধ। জালিয়াতি করলে অ্যাকাউন্ট বাতিল হতে পারে।",
        t_section_3_title: "৩. গেমফিকেশন",
        t_section_3_desc: "হানি ড্রপ এবং XP-এর কোনো আর্থিক মান নেই এবং এগুলো অফলাইনে কেনাবেচা করা সম্ভব নয়। নিয়ম লঙ্ঘনে এগুলো রিসেট করা হতে পারে।",
        t_section_4_title: "৪. মেধা সম্পদ",
        t_section_4_desc: "BeeLesson-এর সকল লোগো ও কন্টেন্ট আমাদের সম্পদ। অনুমতি ছাড়া বাণিজ্যিক উদ্দেশ্যে ব্যবহার করা আইনত দণ্ডনীয়।",
        t_section_5_title: "৫. সেবার পরিবর্তন",
        t_section_5_desc: "আমরা যেকোনো সময় শর্তাবলী পরিবর্তন করার অধিকার রাখি। পরিবর্তনের পর সার্ভিস চালিয়ে যাওয়া নতুন শর্তাবলীতে সম্মতির শামিল।",

        // Auth
        auth_wrong_credentials: "ভুল ইমেইল বা পাসওয়ার্ড। আবার চেষ্টা করুন।",
        auth_account_exists: "এই ইমেইল দিয়ে ইতোমধ্যে একটি অ্যাকাউন্ট তৈরি করা হয়েছে।",
        auth_unverified_email: "আপনার ইমেইল এখনো ভেরিফাই করা হয়নি। অনুগ্রহ করে ইনবক্স চেক করুন।",
        auth_weak_password: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।",
        auth_terms_missing: "চালিয়ে যেতে হলে টার্মস ও কন্ডিশনস-এ সম্মত হতে হবে।",
        auth_generic_error: "কিছু একটা সমস্যা হয়েছে। আবার চেষ্টা করুন।",
        auth_google_failed: "Google দিয়ে লগইন করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
        auth_facebook_failed: "Facebook দিয়ে লগইন করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
        auth_signup_success: "রেজিস্ট্রেশন সফল হয়েছে!",
        auth_email_not_found: "ইমেইল পাওয়া যায়নি",
        auth_signup_success_immediate: "অভিনন্দন! আপনার অ্যাকাউন্টটি সফলভাবে তৈরি হয়েছে।",
        auth_reset_success: "পাসওয়ার্ড রিসেট লিঙ্ক আপনার ইমেইলে পাঠানো হয়েছে। ইনবক্স চেক করুন।",
        auth_reset_title: "পাসওয়ার্ড",
        auth_reset_highlight: "রিসেট",
        auth_reset_suffix: "করুন",
        auth_login_title: "মধু সংগ্রহ শুরু করতে",
        auth_login_highlight: "লগইন",
        auth_login_suffix: "করুন",
        auth_signup_title: "শেখা শুরু করতে মৌচাকে",
        auth_signup_highlight: "যোগ দিন",
        auth_signup_suffix: "",
        auth_name_placeholder: "আপনার পূর্ণ নাম",
        auth_email_placeholder: "আপনার ইমেইল ঠিকানা",
        auth_password_placeholder: "পাসওয়ার্ড",
        auth_remember_me: "মনে রাখুন",
        auth_forgot_password: "পাসওয়ার্ড ভুলে গেছেন?",
        auth_agree_prefix: "আমি",
        auth_agree_terms: "টার্মস এবং কন্ডিশনস",
        auth_agree_and: "ও",
        auth_agree_privacy: "প্রাইভেসি",
        auth_agree_suffix: "পলিসির সাথে একমত",
        auth_send_reset_link: "রিসেট লিঙ্ক পাঠান",
        auth_or: "অথবা",
        auth_back_to_login: "লগইন পেজে ফিরে যান",
        auth_new_user: "নতুন ব্যবহারকারী?",
        auth_already_have_account: "আগে থেকেই অ্যাকাউন্ট আছে?",

        // Dropdowns
        other_gender: "অন্যান্য",
        loc_dhaka: "ঢাকা",
        loc_chattogram: "চট্টগ্রাম",
        loc_rajshahi: "রাজশাহী",
        loc_khulna: "খুলনা",
        loc_barishal: "বরিশাল",
        loc_sylhet: "সিলেট",
        loc_rangpur: "রংপুর",
        loc_mymensingh: "ময়মনসিংহ",
        loc_overseas: "দেশের বাইরে",
        re_practice: "পুনরায় অনুশীলন",

        // Battle War
        battle_create: "নতুন ব্যাটল তৈরি করুন",
        battle_join: "রুমে যোগ দিন",
        waiting_opponent: "প্রতিপক্ষের জন্য অপেক্ষা করা হচ্ছে...",
        battle_mode: "ব্যাটল মোড",
        battle_mode_active: "সক্রিয়",
        battle_mode_inactive: "নিষ্ক্রিয়",
        battle_waiting: "প্রতিপক্ষের জন্য অপেক্ষা করছি...",
        battle_starting: "ব্যাটল শুরু হচ্ছে...",
        battle_lost: "আপনি হেরেছেন",
        select_course: "কোর্স নির্বাচন করুন",
        select_module: "মডিউল নির্বাচন করুন",
        start_battle: "ব্যাটল শুরু করুন",
        back_to_lobby: "লবিতে ফিরে যান",
        battle_won: "🎉 আপনি জিতেছেন!",
        battle_lost: "পরাজিত",
        battle_draw: "ড্র!",
        battle_play_again: "আবার খেলুন",
        battle_cancel: "বাতিল করুন",
        battle_share_code: "এই কোডটি শেয়ার করুন:",
        battle_room_code: "রুম কোড লিখুন...",
        battle_desc: "রিয়েল-টাইম কুইজ প্রতিযোগিতায় আপনার দক্ষতা প্রমাণ করুন!",
        battle_disconnected: "প্রতিপক্ষ ডিসকানেক্ট হয়েছেন"
    },
    en: {
        // Common
        settings: "Settings",
        preferences: "Preferences",
        profile: "Profile",
        notifications: "Notifications",
        courses: "Courses",
        subscription: "Subscription",
        streak: "Daily Streak",
        daily_streak: "Daily Gungun Streak",
        learn: "Learn",
        language: "Language",
        dark_mode: "Dark Mode",
        loading: "Loading...",
        save: "Save",
        cancel: "Cancel",
        confirm: "Confirm",
        go_back: "Back",
        reset: "Reset",
        login: "Login",
        signup: "Sign Up",
        logout: "Logout",
        leaderboard: "Leaderboard",
        shop: "Shop",
        more: "More",
        help: "Help",
        error_fetch_courses: "Failed to fetch courses",
        reset_course: "Reset Course",
        confirm_reset_msg: "Are you sure you want to delete all progress for this course?",
        irreversible: "This action cannot be undone.",
        honey_drop: "Honey Drop",
        king_bee_mode: "Super King Bee",
        queen_bee_mode: "Super Queen Bee",
        only_for_99: "only for ৳99!",
        hearts_added_msg: "new honey drops have been added!",
        heart_refill_5: "5 Honey Drop Refill",
        unlimited_1d: "1 Day Unlimited",
        total_xp: "Total XP",
        select_course: "Select Course",
        add_course: "Add Course",
        your_leaderboard: "Leaderboard",
        unlock_leaderboard_title: "Unlock Leaderboard!",
        unlock_leaderboard_desc: "Earn 100 XP to start competing",
        connect_now: "Connect Now!",
        sun: "Sun",
        mon: "Mon",
        tue: "Tue",
        wed: "Wed",
        thu: "Thu",
        fri: "Fri",
        sat: "Sat",
        my_best: "My Best",
        consistency_score: "Consistency Score",
        perfect_progress: "Perfect Progress!",
        almost_perfect: "Almost Perfect!",
        good_progress: "Good Progress!",
        keep_going: "Keep Going!",
        getting_started: "Getting Started!",
        no_practice_yet: "No Practice Yet",
        daily: "Daily",
        weekly: "Weekly",
        monthly: "Monthly",
        yearly: "Yearly",
        week: "Week",

        streak_tagline_0: "Get started! Build your consistency from today.",
        streak_tagline_1_3: "Great start! Keep up the consistency.",
        streak_tagline_4_10: "Amazing! You're making steady progress. Don't stop.",
        streak_tagline_11_25: "Excellent! Your consistency is getting really strong.",
        streak_tagline_legend: "Incredible! You're a streak legend. Keep it up!",

        // Settings
        pref_settings: "Preference Settings",
        pref_desc: "Customize your personal experience",
        dark_mode_desc: "Use dark theme for eye comfort",
        study_anim: "Study Page Animation",
        study_anim_desc: "Select your preferred bee animation",
        lang_desc: "Select your preferred language",
        sound_effects: "Sound Effects",
        sound_effects_desc: "Turn sound signals on or off during learning",
        sparkle_effects: "Sparkle Effects",
        sparkle_desc: "Create a sparkling atmosphere on correct answers",

        profile_settings: "Profile Settings",
        profile_desc: "Manage your personal information and profile visibility",
        public_profile: "Public Profile",
        public_profile_desc: "Other users will be able to see your learning progress",
        private_profile_msg: "This profile is currently private",
        change_pic: "Change",
        profile_picture: "Profile Picture",
        upload_new_pic: "Upload a new profile picture",
        bouncing_bee: "Bouncing Bee 🐝",
        lounging_bee: "Lounging Bee 🐝💤",
        looking_bee: "Looking Bee 🐝👀",
        flying_bee: "Flying Bee 🐝✈️",
        happy_bee: "Happy Bee 🐝😊",
        random_animation: "Bee Animation",
        no_animation: "No Animation",
        under_development: "This section is under development",
        section_settings: "Settings",
        reset_success: "Course progress has been reset",
        reset_error: "Error resetting course",
        sound_on: "Sound effects enabled",
        sound_off: "Sound effects disabled",
        upload_error: "Error uploading image",
        profile_updated: "Profile updated successfully",
        on: "On",
        off: "Off",
        // Profile
        change_cover: "Change Cover",
        current_streak: "Current Streak",
        buzz_streak: "Daily Streak Buzz",
        days: "Days",
        learner: "Learner",
        welcome_tagline: "Welcome to your learning journey",
        joined: "Joined",
        earned_shield: "Earned Shield",
        level: "Level",
        efficiency: "Efficiency",
        my_courses: "My Courses",
        see_all: "View All",
        progress: "Progress",
        chapters: "Chapters",
        start_course: "Start Course",
        recent_activity: "Recent Activity",
        practice_xp: "Earned XP by completing practice",
        reward_gems: "Received pollen as reward",
        lost_hearts: "Lost honey drops for wrong answer",
        refilled_hearts: "Honey drops refilled",
        no_activity: "No activity records found.",
        edit_profile: "Edit Profile",
        full_name: "Full Name",
        email: "Email",
        designation: "Designation",
        dept: "Department",
        bio: "Bio",
        about_me: "About Me",
        location: "Location",
        phone_number: "Phone Number",
        gender: "Gender",
        male: "Male",
        female: "Female",
        other: "Other",
        age: "Birth Year",
        i_am: "I am",
        student: "Student",
        job_seeker: "Job Seeker",
        job_holder: "Job Holder",
        education: "Education",
        below_class_5: "Below Class 5",
        class_6_10: "Class 6-10",
        intermediate: "Intermediate",
        graduate: "Graduate",
        post_graduate: "Post Graduate",
        update_error: "Problem updating profile.",
        confirm_logout_msg: "Are you sure you want to logout?",
        logout_success: "Successfully logged out",
        logout_error: "Error logging out",

        tab_general: "General",
        tab_analyze: "Analytics",
        tab_activity: "Notification",
        tab_certificates: "Certificates",
        tab_connection: "Connection",
        subtab_my: "My Connections",
        subtab_suggest: "Explore",
        subtab_inbox: "Inbox",
        subtab_battle: "Battle War",
        filter_all: "Connections",
        filter_received: "Received",
        filter_sent: "Sent",
        filter_blocked: "Block List",
        search_learner: "Search learners...",
        send_request: "Send Request",
        pending_requests: "Pending Requests",
        my_connections: "My Connections",
        accept: "Accept",
        decline: "Decline",
        no_connections: "No connections yet",
        learner_profile: "Learner Profile",
        rank: "Rank",
        location: "Location",
        bio: "Bio",
        suggest_connection: "Suggested Friends",
        sent_connection: "Sent Requests",
        suggestions_for_you: "Suggestions for you",
        no_suggestions: "No suggestions yet",
        view_all_suggestions: "View all suggestions",
        no_sent_requests: "No pending requests",
        analysis_locked_title: "Analytics Locked",
        analysis_locked_desc: "Achieve a 3-day learning streak to unlock your performance charts.",
        days_earned: "{count} days earned",
        close: "Close",

        certification: "Certification",
        earned_certificates: "Earned Certificates",
        invite_learner: "Invite Friends",
        invite_success: "Copied!",
        invite_message: "Invite your friends now and get 5 Honey Drops as a bonus!",
        invite_share_cta: "Share",
        invite_share_text: "Hello! I have started learning with BeeLesson. It's Bangladesh's first gamified learning platform, offering a whole new learning experience. So don't delay, join the BeeLesson community today and enjoy a new journey of learning!",
        no_certificates: "You haven't earned any certificates yet.",

        analysis_ov: "Activity Analysis",
        total_time: "Total Time",
        right_answers: "Right Answers",
        wrong_answers: "Wrong Answers",
        daily_xp: "XP Earned",
        accuracy: "Accuracy",
        last_7_days: "Last 7 Days",
        last_15_days: "Last 15 Days",
        last_30_days: "Last 30 Days",
        all_time: "All Time",
        minutes: "Min",
        daily_honey: "Daily Honey Collected",
        earned: "Earned",
        learning_pattern: "Learning Pattern",
        coming_soon: "Coming Soon...",
        lessons_completed: "Lessons Completed",
        activity_log: "Activity Log",
        notifications: "Notifications",
        empty_activity: "No activity found",
        empty_notif: "No new notifications",
        notif_unread: " unread",
        notif_all_read: "All read",
        notif_mark_all: "Mark all as read",
        filter_all_notif: "All",
        filter_achievements: "Achievements",
        filter_social: "Social",
        filter_system: "System",
        no_notifications: "No notifications",
        earlier: "Earlier",

        notif_settings: "Notification Settings",
        // Courses
        courses_title: "Add your favorite",
        courses_highlight: "Courses",
        courses_suffix: "to your list",
        all_courses: "All Courses",
        no_courses_cat: "No courses found in this category.",
        course_rating: "Course Rating",
        students_count: "Student Count",
        search_courses: "Search courses...",
        try_different_filter: "Try a different category or keyword",
        reset_filters: "Reset Filters",
        no_courses_found: "No courses found",
        grid_view: "Grid View",
        list_view: "List View",
        sort_by: "Sort By:",
        sort_popularity: "Popularity",
        sort_rating: "Rating",
        sort_newest: "Newest",

        // Categories
        cat_digital_security_literacy: "Digital Literacy & Security",
        cat_legal_rights: "Legal Awareness & Citizen Rights",
        cat_finance_banking: "Financial Awareness & Smart Banking",
        cat_career_skills: "Career & Skills",
        cat_mental_health: "Mental Health & Self-Development",

        notif_desc: "Control how you receive updates and reminders",
        push_notif: "Push Notifications",
        push_notif_desc: "Get updates directly on your mobile or browser",
        email_notif: "Email Notifications",
        email_notif_desc: "Receive weekly reports and important updates",
        daily_reminder: "Daily Reminder",
        daily_reminder_desc: "Get a daily reminder to keep learning",
        active_membership: "Active Membership",
        no_active_membership: "No Active Membership",
        expires_on: "Expires on",
        unlock_premium_visit_shop: "Unlock premium features, visit shop",
        cancelled_not_renew: "⚠ Cancelled (Will not renew)",
        cancel_membership: "Cancel Membership",
        cancel_membership_msg: "Are you sure you want to cancel? You will keep your benefits until the end of the current period, and it will not renew.",
        yes_cancel: "Yes, Cancel",
        successfully_cancelled: "Successfully cancelled",
        error_cancelling: "Error cancelling",
        search_chat: "Search chat...",
        email_notif_desc: "Get weekly progress reports and important updates",

        course_settings: "Course Settings",
        course_settings_desc: "Manage your enrolled courses",
        completed: "Completed",
        no_courses: "No courses found",
        no_courses_desc: "You haven't enrolled in any courses yet.",
        warning_reset: "Warning: Resetting cannot be undone.",
        error_update_settings: "Failed to update settings",
        select: "Select",

        // Shop
        shop_title: "BeeLesson Shop",
        shop_subtitle: "Enrich your learning experience",
        super_membership: "Super Membership",
        super_desc: "You are now enjoying unlimited honey drops and an ad-free experience.",
        active_super: "Super Membership Active",
        unlimited_hearts: "Unlimited Honey Drops",
        ad_free: "Ad-Free Learning",
        quick_progress: "Quick Progress",
        special_badge: "Special Badge",
        monthly: "Monthly",
        yearly: "Yearly",
        discount: "-20%",
        gem_exchange: "Pollen Exchange",
        exchange: "Exchange",
        gem_packs: "Pollen Packs",
        popular: "Popular",
        best_value: "Best Value",
        confirm_payment: "Confirm Payment",
        payment_desc: "Select a payment method to complete your order",
        order_summary: "Order Summary",
        item: "Item",
        total_price: "Total Price",
        pay_now: "Complete Payment",
        insufficient_gems: "You don't have enough pollen.",
        hearts_added: " new honey drops have been added!",
        hearts_added_msg: "honey drops added",
        gems_added: " pollen grains have been added!",
        congrats_premium: "Congratulations! You are now a Super subscriber.",
        payment_failed: "Payment failed. Please try again.",
        loading_shop: "Loading...",
        active: "Active",
        activate: "Activate",
        bkash: "bKash",
        nagad: "Nagad",
        quick_honey_drop: "Quick Honey Drop",
        enjoy_1day_unlimited: "Enjoy unlimited honey drops for a full day!",
        recharge_1day: "Recharge",
        exchange_success_title: "Success!",
        exchange_success_desc: "Your pollen has been successfully converted.",
        insufficient_pollen_title: "Not Enough Pollen",
        insufficient_pollen_desc: "At least {amount} pollen is required for exchange.",
        start_learning_earn_pollen: "Start Learning",
        view_mode: "View Mode",
        not_now: "Not Now",
        confirm_exchange_title: "Confirm Exchange",
        confirm_exchange_desc: "Confirm to exchange pollen for honey drops",
        yes_confirm: "Yes, Confirm",
        no: "No",
        unlocked_all_features: "All features unlocked",
        unlimited_hearts_msg: "Learn with unlimited honey drops",
        unlimited_hearts_active_msg: "Your unlimited honey drops are already active. 👑",
        male_bee_title: "King Bee",
        female_bee_title: "Queen Bee",
        queen_bee_feature_1: "Learning won't stop even if you make mistakes. Unlimited honey drops.",
        please_login: "Please login to continue.",
        unlimited_active_already: "Unlimited honey drops are already active.",
        already_in_mode: "You are currently in {mode} mode! 👑",
        conversion_error: "Error converting.",
        data_not_found: "Data not found.",
        something_went_wrong: "Sorry, something went wrong.",
        session_not_found: "Session not found. Please login again.",
        payment_processing: "Processing payment...",
        subscription_success: "Subscription successful! You are now a member! 👑",
        oneday_recharge_success: "1-day recharge successful! Enjoy unlimited honey drops 🍯",
        payment_process_failed: "Could not process payment.",
        write_msg: "Write Message...",
        today: "Today",
        yesterday: "Yesterday",
        delete_msg: "Delete",
        survey_continue: "Continue",
        survey_complete: "Complete",
        step: "Step",

        // Gem Pack Labels
        gem_pocket: "Pollen Pocket",
        gem_chest: "Pollen Chest",
        gem_cart: "Pollen Cart",
        gem_vault: "Pollen Vault",
        pollen: "Pollen",

        // Leaderboard Page
        unlock_leaderboard: "Unlock Leaderboard",
        reach_xp_to_unlock: "Earn {xp} more Pollen to join the competition.",
        xp_earned_so_far: "{xp} Pollen earned",
        target_xp: "{xp} Pollen",
        how_to_earn_xp: "How to earn Pollen?",
        earn_xp_desc: "You earn Pollen by completing chapters or quizzes. Accurate answers give more Pollen.",
        bee_ranks: "Bee Ranks",
        bee_ranks_desc: "Bee Kid → Warrior → Master → Legendary. Top learners advance weekly.",
        start_competition: "Start Competing",
        start_competition_desc: "Compete with friends and list yourself among the best learners.",
        start_learning_btn: "Start Learning",
        reached_legendary: "You have reached Bee Legendary! 🎉",
        shop: "Shop",
        leaderboard: "Leaderboard",
        login_btn: "Login",

        // Hero
        hero_badge: "Short on time, big on interest?",
        hero_title_br: "Learn Easily and Free",
        hero_highlight: "The Attractive Way to Get Skilled!",
        hero_description: "Keep learning whenever and wherever you want — in an easy, fun, and effective way.",
        start_learning: "Start Learning",

        // Landing Page Generic
        proven_title: "Scientifically Proven",
        proven_desc: "Our teaching methods are research-based and effective. Each lesson is designed so you can learn quickly and in an enjoyable way.",
        footer_copy: "2024 BeeLesson. All rights reserved.",

        reset_filters: "Reset all filters",

        // Help Center
        help_center: "Help Center",
        how_can_we_help: "How can we help you?",
        search_placeholder: "Type your question (e.g., certificate, payment...)",
        faq_title: "Frequently Asked Questions",
        faq_subtitle: "Find the information you need below",
        need_direct_help: "Need direct help?",
        mail_support_desc: "If you have any specific questions, feel free to email our support team.",
        no_results_found: "No results found relating to",
        help_footer: "© 2024 BeeLesson Help Center",
        clear_search: "Clear search",

        // Privacy Page
        privacy_policy: "Privacy Policy",
        privacy_desc: "Your data security is our top priority. Here is how we collect and use your information at BeeLesson:",
        p_section_1_title: "1. Information Collection",
        p_section_1_desc: "We collect your name, email, profile picture, birth year, and professional info. We also track your learning progress, streaks, and honey drops.",
        p_section_2_title: "2. How We Use Data",
        p_section_2_desc: "We use this information to personalize your learning, calculate leaderboard rankings, and ensure the security of the platform.",
        p_section_3_title: "3. Data Sharing",
        p_section_3_desc: "We never sell your data. Only your public profile components (name, streak, progress) are visible to other learners if enabled.",
        p_section_4_title: "4. Data Security",
        p_section_4_desc: "We use modern services like Supabase to keep your data encrypted and safe. Your privacy is sacred to us.",
        p_section_5_title: "5. Your Control",
        p_section_5_desc: "You can update or delete your profile anytime. You can also set your profile to 'Private' to hide your activity from others.",
        p_contact_us: "Contact: support@beelesson.com",

        // Terms Page
        terms_title: "Terms and Conditions",
        terms_desc: "Welcome to BeeLesson. By using our services, you agree to the following terms and conditions. Please read them carefully.",
        t_section_1_title: "1. Account & Registration",
        t_section_1_desc: "You must provide accurate information to create an account. You are responsible for maintaining the confidentiality of your account.",
        t_section_2_title: "2. Usage Rules",
        t_section_2_desc: "You may not copy, modify, or distribute any content from BeeLesson without our permission. Fraudulent activity may lead to account termination.",
        t_section_3_title: "3. Gamification",
        t_section_3_desc: "Honey Drops and XP have no monetary value and cannot be traded offline. We reserve the right to reset counts in case of manipulation.",
        t_section_4_title: "4. Intellectual Property",
        t_section_4_desc: "All logos, graphics, and course content are the property of BeeLesson. Commercial use without permission is strictly prohibited.",
        t_section_5_title: "5. Service Changes",
        t_section_5_desc: "We reserve the right to modify these terms at any time. Continued use of the platform constitutes agreement to the updated terms.",

        // Leaderboard fixes
        complete_xp_to_join: "Complete +{xp} Pollen to join {tier} league",
        leaderboard_table_rank: "#",
        leaderboard_table_learner: "Learner",
        leaderboard_table_progress: "Progress",
        leaderboard_table_pollen: "Total Pollen",
        empty_tier: "No learners in this league yet. Start learning and make your place!",
        leaderboard_share_msg: "I'm ranked #{rank} in the {tier} Bee on BeeLesson! Can you beat my {xp} Pollen?",
        share_rank_tooltip: "Share your rank",

        // Auth
        auth_wrong_credentials: "Wrong Email or Password. Please try again.",
        auth_account_exists: "An account has already been created with this email.",
        auth_unverified_email: "Your email is not verified yet. Please check your inbox.",
        auth_weak_password: "Password must be at least 6 characters.",
        auth_terms_missing: "You must agree to the terms and conditions to continue.",
        auth_generic_error: "Something went wrong. Please try again.",
        auth_google_failed: "Failed to login with Google. Please try again.",
        auth_facebook_failed: "Failed to login with Facebook. Please try again.",
        auth_signup_success: "Registration successful!",
        auth_email_not_found: "Email not found",
        auth_signup_success_immediate: "Congratulations! Your account has been successfully created.",
        auth_reset_success: "Password reset link sent to your email. Check your inbox.",
        auth_reset_title: "Password",
        auth_reset_highlight: "Reset",
        auth_reset_suffix: "",
        auth_login_title: "To start collecting honey",
        auth_login_highlight: "Login",
        auth_login_suffix: "",
        auth_signup_title: "Join the honeycomb to start",
        auth_signup_highlight: "Learning",
        auth_signup_suffix: "",
        auth_name_placeholder: "Your Full Name",
        auth_email_placeholder: "Your Email Address",
        auth_password_placeholder: "Password",
        auth_remember_me: "Remember Me",
        auth_forgot_password: "Forgot Password?",
        auth_agree_prefix: "I agree to the",
        auth_agree_terms: "Terms and Conditions",
        auth_agree_and: "and",
        auth_agree_privacy: "Privacy",
        auth_agree_suffix: "Policy",
        auth_send_reset_link: "Send Reset Link",
        auth_or: "Or",
        auth_back_to_login: "Back to Login",
        auth_new_user: "New user?",
        auth_already_have_account: "Already have an account?",

        // Dropdowns
        other_gender: "Other",
        loc_dhaka: "Dhaka",
        loc_chattogram: "Chattogram",
        loc_rajshahi: "Rajshahi",
        loc_khulna: "Khulna",
        loc_barishal: "Barishal",
        loc_sylhet: "Sylhet",
        loc_rangpur: "Rangpur",
        loc_mymensingh: "Mymensingh",
        loc_overseas: "Overseas",
        save_percentage_yearly: "Save 16%",
        order_details: "Order Details",
        payment_method: "Payment Method",
        tax: "TAX",
        total_due_today: "Grand Total",
        discount_label: "Discount",
        promo_success_msg: "Success",
        enter_promo_code: "Coupon code",
        apply: "Apply",
        remove: "Remove",
        re_practice: "Re-practice",

        // Battle War
        battle_create: "Create Battle",
        battle_join: "Join Room",
        waiting_opponent: "Waiting for opponent...",
        battle_mode: "Battle Mode",
        battle_mode_active: "Active",
        battle_mode_inactive: "Inactive",
        battle_starting: "Battle starting...",
        battle_won: "🎉 You Won!",
        battle_lost: "Defeated",
        select_course: "Select Course",
        select_module: "Select Module",
        start_battle: "Start Battle",
        back_to_lobby: "Back to Lobby",
        battle_draw: "Draw!",
        battle_play_again: "Play Again",
        battle_cancel: "Cancel",
        battle_share_code: "Share this code:",
        battle_room_code: "Enter room code...",
        battle_desc: "Prove your knowledge in a real-time quiz duel!",
        battle_disconnected: "Opponent disconnected"
    }
};




const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return saved || 'bn';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        // Force document language attribute update
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => {
        return translations[language][key] !== undefined ? translations[language][key] : key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'bn' ? 'en' : 'bn');
    };

    const formatNumber = (num) => {
        if (language === 'en') return num;
        const bnNums = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
        return String(num).replace(/[0-9]/g, digit => bnNums[digit]);
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, formatNumber }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
