import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    bn: {
        // Common
        settings: "সেটিংস",
        preferences: "প্রেফারেন্স",
        profile: "প্রোফাইল",
        notifications: "নোটিফিকেশন",
        courses: "কোর্স",
        subscription: "সাবস্ক্রিপশন",
        streak: "দৈনিক স্ট্রিক",
        daily_streak: "দৈনিক গুনগুন স্ট্রিক",
        learn: "শিখুন",
        language: "ভাষা",
        dark_mode: "ডার্ক মুড",
        loading: "লোড হচ্ছে...",
        save: "সংরক্ষণ করুন",
        cancel: "বাতিল",
        confirm: "নিশ্চিত",
        reset: "রিসেট",
        login: "লগইন",
        signup: "সাইন আপ",
        logout: "লগআউট",
        error_fetch_courses: "কোর্স তালিকা লোড করতে সমস্যা হয়েছে",
        reset_course: "কোর্স রিসেট",
        confirm_reset_msg: "আপনি কি নিশ্চিত যে এই কোর্সের সকল প্রগতি মুছে ফেলতে চান?",
        irreversible: "এটি আর ফিরিয়ে আনা সম্ভব নয়।",
        honey_drop: "হানি ড্রপ",
        king_bee_mode: "কিং বী",
        queen_bee_mode: "কুইন বী",
        only_for_99: "হন মাত্র 99 টাকায়!",
        hearts_added_msg: "নতুন হানি ড্রপ যোগ করা হয়েছে!",
        heart_refill_5: "5টি হানি ড্রপ রিফিল",
        unlimited_1d: "১ দিনের আনলিমিটেড",

        // Settings
        pref_settings: "ব্যক্তিগত অভিজ্ঞতা",
        pref_desc: "আপনার ব্যক্তিগত ব্যবহারের অভিজ্ঞতা কাস্টমাইজ করুন",
        dark_mode_desc: "চোখের আরামের জন্য কালো থিম ব্যবহার করুন",
        study_anim: "স্টাডি পেজ অ্যানিমেশন",
        study_anim_desc: "আপনার পছন্দের মৌমাছি অ্যানিমেশন নির্বাচন করুন",
        lang_desc: "আপনার পছন্দের ভাষা নির্বাচন করুন",
        sound_effects: "সাউন্ড ইফেক্ট",
        sound_effects_desc: "শেখার সময় শব্দ সংকেত চালু বা বন্ধ রাখুন",
        sparkle_effects: "স্পার্কল ইফেক্টস",
        sparkle_desc: "সঠিক উত্তরের সময় ঝলমলে আবহ তৈরি করুন",

        profile_settings: "প্রোফাইল সেটিংস",
        profile_desc: "আপনার ব্যক্তিগত তথ্য এবং প্রোফাইল দৃশ্যমানতা পরিচালনা করুন",
        public_profile: "পাবলিক প্রোফাইল",
        public_profile_desc: "অন্যান্য ব্যবহারকারীরা আপনার শেখার অগ্রগতি দেখতে পারবে",
        change_pic: "পরিবর্তন করুন",
        profile_picture: "প্রোফাইল ছবি",
        upload_new_pic: "একটি নতুন প্রোফাইল ছবি আপলোড করুন",
        bouncing_bee: "বাউন্সিং বী 🐝",
        lounging_bee: "লাউঞ্জিং বী 🐝💤",
        looking_bee: "লুকিং বী 🐝👀",
        flying_bee: "ফ্লাইং বী 🐝✈️",
        happy_bee: "হ্যাপি বী 🐝😊",
        random_animation: "বী অ্যানিমেশন",
        no_animation: "কোনো অ্যানিমেশন নয়",
        under_development: "এই সেকশনটি বর্তমানে ডেভেলপমেন্টাধীন আছে",
        section_settings: "সেটিংস",
        reset_success: "কোর্স প্রগতি রিসেট করা হয়েছে",
        reset_error: "রিসেট করতে সমস্যা হয়েছে",
        sound_on: "সাউন্ড ইফেক্ট চালু করা হয়েছে",
        sound_off: "সাউন্ড ইফেক্ট বন্ধ করা হয়েছে",
        upload_error: "ছবি আপলোড করতে সমস্যা হয়েছে",
        profile_updated: "প্রোফাইল আপডেট করা হয়েছে",
        on: "চালু",
        off: "বন্ধ",
        // Profile
        change_cover: "কভার পরিবর্তন করুন",
        current_streak: "বর্তমান স্ট্রিক",
        buzz_streak: "দৈনিক গুনগুন স্ট্রিক",
        days: "দিন",
        learner: "শিক্ষার্থী",
        welcome_tagline: "শেখার যাত্রায় আপনাকে স্বাগতম",
        joined: "যোগদান",
        earned_shield: "অর্জিত শিল্ড",
        level: "লেভেল",
        efficiency: "নির্ভুলতা",
        my_courses: "আমার কোর্সসমূহ",
        see_all: "সবগুলো দেখুন",
        progress: "অগ্রগতি",
        chapters: "অধ্যায়",
        start_course: "কোর্স শুরু করুন",
        recent_activity: "সাম্প্রতিক কার্যকলাপ",
        practice_xp: "অনুশীলন সম্পন্ন করে XP পেয়েছেন",
        reward_gems: "পুরস্কারস্বরূপ পরাগরেণু পেয়েছেন",
        lost_hearts: "ভুল উত্তরের জন্য হানি ড্রপ হারিয়েছেন",
        refilled_hearts: "হানি ড্রপ রিফিল হয়েছে",
        no_activity: "কোনো কার্যকলাপের রেকর্ড পাওয়া যায়নি।",
        edit_profile: "প্রোফাইল সম্পাদন করুন",
        full_name: "পুরো নাম",
        email: "ইমেইল",
        designation: "পদবী",
        dept: "বিভাগ/দপ্তর",
        bio: "আপনার সম্পর্কে",
        about_me: "নিজের সম্পর্কে লিখুন",
        location: "অবস্থান",
        phone_number: "ফোন নম্বর",
        gender: "লিঙ্গ",
        male: "পুরুষ",
        female: "নারী",
        other: "অন্যান্য",
        age: "জন্ম সাল",
        i_am: "আমি একজন",
        student: "শিক্ষার্থী",
        job_seeker: "চাকরিপ্রার্থী",
        job_holder: "চাকরিজীবী",
        education: "শিক্ষাগত যোগ্যতা",
        below_class_5: "৫ম শ্রেণীর নিচে",
        class_6_10: "৬ষ্ঠ-১০ম শ্রেণী",
        intermediate: "এইচএসসি/ডিপ্লোমা",
        graduate: "স্নাতক",
        post_graduate: "স্নাতকোত্তর",
        update_error: "প্রোফাইল আপডেট করতে সমস্যা হয়েছে।",
        confirm_logout_msg: "আপনি কি নিশ্চিত যে লগআউট করতে চান?",
        logout_success: "সাফল্যের সাথে লগআউট করা হয়েছে",
        logout_error: "লগআউট করতে সমস্যা হয়েছে",

        notif_settings: "নোটিফিকেশন সেটিংস",
        notif_desc: "আপনি কিভাবে আপডেট এবং স্মরণিকা পাবেন তা নিয়ন্ত্রণ করুন",
        push_notif: "পুশ নোটিফিকেশন",
        push_notif_desc: "আপনার মোবাইল বা ব্রাউজারে সরাসরি আপডেট পান",
        email_notif: "ইমেল নোটিফিকেশন",
        email_notif_desc: "সাপ্তাহিক প্রগতি রিপোর্ট এবং গুরুত্বপূর্ণ আপডেট পান",
        daily_reminder: "ডেইলি রিমাইন্ডার",
        daily_reminder_desc: "প্রতিদিন শিখতে থাকার জন্য একটি স্মারক পান",

        course_settings: "কোর্স সেটিংস",
        course_settings_desc: "আপনার এনরোল করা কোর্সসমূহ পরিচালনা করুন",
        completed: "সম্পন্ন",
        no_courses: "কোনো কোর্স পাওয়া যায়নি",
        no_courses_desc: "আপনি এখনও কোনো কোর্সে এনরোল করেননি।",
        warning_reset: "সতর্কতা: প্রগতি রিসেট বা কোর্স ডিলিট করলে তা আর পুনরুদ্ধার করা সম্ভব নয়।",

        // Shop
        shop_title: "বী-লেসন শপ",
        shop_subtitle: "আপনার শেখার অভিজ্ঞতাকে আরও সমৃদ্ধ করুন",
        super_membership: "সুপার মেম্বারশিপ",
        super_desc: "আপনি এখন আনলিমিটেড হানি ড্রপ এবং অ্যাড-ফ্রি অভিজ্ঞতা উপভোগ করছেন।",
        active_super: "সুপার সদস্যপদ সক্রিয়",
        unlimited_hearts: "আনলিমিটেড হানি ড্রপ",
        ad_free: "অ্যাড-ফ্রি লার্নিং",
        quick_progress: "দ্রুত প্রগ্রেস",
        special_badge: "স্পেশাল ব্যাজ",
        monthly: "মাসিক",
        yearly: "বার্ষিক",
        discount: "-20%",
        gem_exchange: "পরাগরেণু এক্সচেঞ্জ",
        exchange: "এক্সচেঞ্জ",
        gem_packs: "পরাগরেণু প্যাক",
        popular: "জনপ্রিয়",
        best_value: "সেরা মূল্য",
        confirm_payment: "পেমেন্ট নিশ্চিত করুন",
        payment_desc: "আপনার অর্ডারটি সম্পন্ন করতে পেমেন্ট মেথড নির্বাচন করুন",
        order_summary: "অর্ডার সামারি",
        item: "আইটেম",
        total_price: "মোট মূল্য",
        pay_now: "পেমেন্ট সম্পন্ন করুন",
        insufficient_gems: "আপনার কাছে যথেষ্ট পরাগরেণু নেই।",
        hearts_added: "টি নতুন হানি ড্রপ যোগ করা হয়েছে!",
        gems_added: "টি পরাগরেণু যোগ করা হয়েছে!",
        congrats_premium: "অভিনন্দন! আপনি এখন সুপার সাবস্ক্রাইবার।",
        payment_failed: "পেমেন্ট সফল হয়নি। পুনরায় চেষ্টা করুন।",
        loading_shop: "লোড হচ্ছে...",

        // Gem Pack Labels
        gem_pocket: "পরাগরেণু পকেট",
        gem_chest: "পরাগরেণু চেস্ট",
        gem_cart: "পরাগরেণু কার্ট",
        gem_vault: "পরাগরেণু ভল্ট",
        pollen: "পরাগরেণু",

        // Navbar
        learn: "শিখুন",
        shop: "শপ",
        leaderboard: "লিডারবোর্ড",
        login_btn: "লগইন করুন",

        // Courses
        courses_title: "আপনার পছন্দের",
        courses_highlight: "কোর্সসমূহ",
        courses_suffix: "যুক্ত করুন",
        all_courses: "সব কোর্স",
        no_courses_cat: "এই ক্যাটাগরিতে কোনো কোর্স পাওয়া যায়নি।",

        // Categories
        cat_digital_security_literacy: "ডিজিটাল লিটারেসি ও নিরাপত্তা",
        cat_legal_rights: "আইনি সচেতনতা ও নাগরিক অধিকার",
        cat_finance_banking: "আর্থিক সচেতনতা ও স্মার্ট ব্যাংকিং",
        cat_career_skills: "ক্যারিয়ার ও দক্ষতা",
        cat_mental_health: "মানসিক স্বাস্থ্য ও আত্মউন্নয়ন",

        // Landing Page Generic
        proven_title: "বৈজ্ঞানিকভাবে প্রমাণিত",
        proven_desc: "আমাদের পাঠদান পদ্ধতি গবেষণালব্ধ এবং কার্যকর। প্রতিটি পাঠ ডিজাইন করা হয়েছে যাতে আপনি দ্রুত এবং আনন্দদায়ক উপায়ে শিখতে পারেন।",
        footer_copy: "2024 BeeLesson. সকল স্বত্ব সংরক্ষিত।",
        
        // New Search/Filter strings
        search_courses: "কোর্স খুঁজুন...",
        courses_found: "টি কোর্স পাওয়া গেছে",
        no_courses_found: "দুঃখিত, কোনো কোর্স খুঁজে পাওয়া যায়নি",
        try_different_filter: "দয়া করে অন্য কোনো বিষয় বা কি-ওয়ার্ড দিয়ে চেষ্টা করুন",
        reset_filters: "সব রিসেট করুন"
    },
    en: {
        // Common
        settings: "Settings",
        preferences: "Preferences",
        profile: "Profile",
        notifications: "Notifications",
        courses: "Courses",
        subscription: "Subscription",
        streak: "Daily Streak",
        daily_streak: "Daily Gungun Streak",
        learn: "Learn",
        language: "Language",
        dark_mode: "Dark Mode",
        loading: "Loading...",
        save: "Save",
        cancel: "Cancel",
        confirm: "Confirm",
        reset: "Reset",
        login: "Login",
        signup: "Sign Up",
        logout: "Logout",
        error_fetch_courses: "Error loading course list",
        reset_course: "Reset Course",
        confirm_reset_msg: "Are you sure you want to delete all progress for this course?",
        irreversible: "This action cannot be undone.",
        honey_drop: "Honey Drop",
        king_bee_mode: "King Bee Mode",
        queen_bee_mode: "Queen Bee Mode",
        only_for_99: "only for ৳99!",
        hearts_added_msg: "new honey drops have been added!",
        heart_refill_5: "5 Honey Drop Refill",
        unlimited_1d: "1 Day Unlimited",

        // Settings
        pref_settings: "Preference Settings",
        pref_desc: "Customize your personal experience",
        dark_mode_desc: "Use dark theme for eye comfort",
        study_anim: "Study Page Animation",
        study_anim_desc: "Select your preferred bee animation",
        lang_desc: "Select your preferred language",
        sound_effects: "Sound Effects",
        sound_effects_desc: "Turn sound signals on or off during learning",
        sparkle_effects: "Sparkle Effects",
        sparkle_desc: "Create a sparkling atmosphere on correct answers",

        profile_settings: "Profile Settings",
        profile_desc: "Manage your personal information and profile visibility",
        public_profile: "Public Profile",
        public_profile_desc: "Other users will be able to see your learning progress",
        change_pic: "Change",
        profile_picture: "Profile Picture",
        upload_new_pic: "Upload a new profile picture",
        bouncing_bee: "Bouncing Bee 🐝",
        lounging_bee: "Lounging Bee 🐝💤",
        looking_bee: "Looking Bee 🐝👀",
        flying_bee: "Flying Bee 🐝✈️",
        happy_bee: "Happy Bee 🐝😊",
        random_animation: "Bee Animation",
        no_animation: "No Animation",
        under_development: "This section is under development",
        section_settings: "Settings",
        reset_success: "Course progress has been reset",
        reset_error: "Error resetting course",
        sound_on: "Sound effects enabled",
        sound_off: "Sound effects disabled",
        upload_error: "Error uploading image",
        profile_updated: "Profile updated successfully",
        on: "On",
        off: "Off",
        // Profile
        change_cover: "Change Cover",
        current_streak: "Current Streak",
        buzz_streak: "Buzz Streak",
        days: "Days",
        learner: "Learner",
        welcome_tagline: "Welcome to your learning journey",
        joined: "Joined",
        earned_shield: "Earned Shield",
        level: "Level",
        efficiency: "Efficiency",
        my_courses: "My Courses",
        see_all: "View All",
        progress: "Progress",
        chapters: "Chapters",
        start_course: "Start Course",
        recent_activity: "Recent Activity",
        practice_xp: "Earned XP by completing practice",
        reward_gems: "Received pollen as reward",
        lost_hearts: "Lost honey drops for wrong answer",
        refilled_hearts: "Honey drops refilled",
        no_activity: "No activity records found.",
        edit_profile: "Edit Profile",
        full_name: "Full Name",
        email: "Email",
        designation: "Designation",
        dept: "Department",
        bio: "Bio",
        about_me: "About Me",
        location: "Location",
        phone_number: "Phone Number",
        gender: "Gender",
        male: "Male",
        female: "Female",
        other: "Other",
        age: "Birth Year",
        i_am: "I am",
        student: "Student",
        job_seeker: "Job Seeker",
        job_holder: "Job Holder",
        education: "Education",
        below_class_5: "Below Class 5",
        class_6_10: "Class 6-10",
        intermediate: "Intermediate",
        graduate: "Graduate",
        post_graduate: "Post Graduate",
        update_error: "Problem updating profile.",
        confirm_logout_msg: "Are you sure you want to logout?",
        logout_success: "Successfully logged out",
        logout_error: "Error logging out",

        notif_settings: "Notification Settings",
        // Courses
        courses_title: "Add your favorite",
        courses_highlight: "Courses",
        courses_suffix: "to your list",
        all_courses: "All Courses",
        no_courses_cat: "No courses found in this category.",

        // Categories
        cat_digital_security_literacy: "Digital Literacy & Security",
        cat_legal_rights: "Legal Awareness & Citizen Rights",
        cat_finance_banking: "Financial Awareness & Smart Banking",
        cat_career_skills: "Career & Skills",
        cat_mental_health: "Mental Health & Self-Development",

        notif_desc: "Control how you receive updates and reminders",
        push_notif: "Push Notifications",
        push_notif_desc: "Get updates directly on your mobile or browser",
        email_notif: "Email Notifications",
        email_notif_desc: "Receive weekly reports and important updates",
        daily_reminder: "Daily Reminder",
        daily_reminder_desc: "Get a daily reminder to keep learning",
        email_notif_desc: "Get weekly progress reports and important updates",

        course_settings: "Course Settings",
        course_settings_desc: "Manage your enrolled courses",
        completed: "Completed",
        no_courses: "No courses found",
        no_courses_desc: "You haven't enrolled in any courses yet.",
        warning_reset: "Warning: Resetting progress or deleting a course cannot be undone.",

        // Shop
        shop_title: "BeeLesson Shop",
        shop_subtitle: "Enrich your learning experience",
        super_membership: "Super Membership",
        super_desc: "You are now enjoying unlimited honey drops and an ad-free experience.",
        active_super: "Super Membership Active",
        unlimited_hearts: "Unlimited Honey Drops",
        ad_free: "Ad-Free Learning",
        quick_progress: "Quick Progress",
        special_badge: "Special Badge",
        monthly: "Monthly",
        yearly: "Yearly",
        discount: "-20%",
        gem_exchange: "Pollen Exchange",
        exchange: "Exchange",
        gem_packs: "Pollen Packs",
        popular: "Popular",
        best_value: "Best Value",
        confirm_payment: "Confirm Payment",
        payment_desc: "Select a payment method to complete your order",
        order_summary: "Order Summary",
        item: "Item",
        total_price: "Total Price",
        pay_now: "Complete Payment",
        insufficient_gems: "You don't have enough pollen.",
        hearts_added: " new honey drops have been added!",
        gems_added: " pollen grains have been added!",
        congrats_premium: "Congratulations! You are now a Super subscriber.",
        payment_failed: "Payment failed. Please try again.",
        loading_shop: "Loading...",

        // Gem Pack Labels
        gem_pocket: "Pollen Pocket",
        gem_chest: "Pollen Chest",
        gem_cart: "Pollen Cart",
        gem_vault: "Pollen Vault",
        pollen: "Pollen",

        // Navbar
        learn: "Learn",
        shop: "Shop",
        leaderboard: "Leaderboard",
        login_btn: "Login",

        // Hero
        hero_badge: "Short on time, big on interest?",
        hero_title_br: "Learn Easily and Free",
        hero_highlight: "The Attractive Way to Get Skilled!",
        hero_description: "Keep learning whenever and wherever you want — in an easy, fun, and effective way.",
        start_learning: "Start Learning",

        // Landing Page Generic
        proven_title: "Scientifically Proven",
        proven_desc: "Our teaching methods are research-based and effective. Each lesson is designed so you can learn quickly and in an enjoyable way.",
        footer_copy: "2024 BeeLesson. All rights reserved.",

        // New Search/Filter strings
        search_courses: "Search courses...",
        courses_found: "courses found",
        no_courses_found: "No courses found",
        try_different_filter: "Try searching with a different keyword or category",
        reset_filters: "Reset all filters"
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return saved || 'bn';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        // Force document language attribute update
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'bn' ? 'en' : 'bn');
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
